### ISSUE TITLE
reference to itself is generated into imports

### ISSUE THREAD

**Issue by capaj** [YassinEldeeb/prisma-tgql-types-gen#17]
If I have a field which references the current table, there is an import generated which causes havoc.
For example like here:
```
model Comment { 
  id             String    @id @default(cuid())
 replyTo           Story?     @relation("comments_reply_to_id", fields: [replyToId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  replyToId         String?    @map("reply_to_id")
}
```
![image](https://user-images.githubusercontent.com/1305378/144397633-b27042ad-ad3a-4889-9f2c-305863d83a8e.png)

this cause a TS error and runtime type error

**Comment by YassinEldeeb** [comment]
fixing it.

**Comment by YassinEldeeb** [comment]
Fixed

**Comment by capaj** [comment]
it is still broken in 1.4.20 when you use `exportedNameSuffix` option.

**Comment by YassinEldeeb** [comment]
Yeah I forgot to do that too while developing 😅, This generator makes you import whatever you want without overwriting it and other more safe areas, It's one of the most important features in this generator that there's an introspection happening to the generated TS code to suistain your changes and correct you if you mess up the types.
